import type { Metadata } from "next";
import "@/assets/styles/index.css";
import { Header } from "@/components/widgets/header/Header";
import { Footer } from "@/components/widgets/footer/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en">
      <body>
        <div className="wrapper">
          <main className="content">
            <Header/>
            {children}
            <Footer/>
          </main>
        </div>
      </body>
    </html>
  );
}
