import type { Metadata } from "next";
import "@/assets/styles/index.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en">
      <body>
        <div className="wrapper">
          <main className="content">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
