import type { Metadata } from "next";
import "@/assets/styles/index.css";
import { Header } from "@/components/widgets/header/Header";
import { Footer } from "@/components/widgets/footer/Footer";
import { roboto, inter, montserrat } from '@/assets/fonts/fonts';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} ${inter.variable} ${montserrat.variable}`}>
        <div className="wrapper">
          <Header />
          <main className="content">{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
